baseURL = "https://sh0seo.github.io/"
languageCode = "en-us"
title = "my side projects"
paginate = 10
theme = "cactus"
disqusShortname = "devdotlog"
googleAnalytics = "UA-156450601-1"
googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
colortheme = "classic" # dark, light, white, or classic
rss = true # generate rss feed. default value is false

[Author]
  name = "about sh0seo"
  bio = "Just do it."
  avatar = "img/logo.png"

[Params]
  subtitle = "개발자 블로그"
  description = "뭐라도 좀 적고, 써야 남지 않을까? / Site Project 정리용."
  copyright = "sh0seo All rights reserved."
  dateformat = "2006-01-02" # Change the format of dates
  showAllPostsOnHomePage = true
  postsOnHomePage = 100
  mainSection = "posts"
  highlight = true
  #mathjax = true # Enable MathJax
  #mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
  #mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  #googleFontsLink = "https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700" # Load Google Fonts

  showProjectsList = false
  projectsUrl = "https://github.com/monkeyWzr"

  [params.comments]
    enabled = true # default
    engine = "disqus" # more supported engines will be added.

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
[[params.social]]
  name = "github"
  link = "https://github.com/sh0seo/"

[[params.social]]
  name = "email"
  link = "ssh0702@gmail.com"  # no need for "mailto:" in the head

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20

[permalinks]
  posts = "/:title/"