name: jekyll deploy

on:
  push:
    branches: [ master ]
jobs:
  jekyll:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-      
          
    # Standard usage
      name: Jekyll Actions
    - uses: helaili/jekyll-action@2.0.4
      env:
        JEKYLL_PAT: ${{ secrets.HUGO_BLOG_TOKEN }}
      with:
        target_branch: 'gh-pages'
