name: jekyll deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    #- name: Hugo setup
    #  uses: peaceiris/actions-hugo@v2.4.12
   
    #- name: Build Hugo Site
    #  run: hugo --minify

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
          github_token: ${{ secrets.HUGO_BLOG_TOKEN }}
          publish_dir: ./_site
