name: jekyll deploy

on:
  push:
    branches: [ master ]
jobs:
  jekyll:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    # Standard usage
    - uses:  helaili/jekyll-action@2.0.3
      env:
        JEKYLL_PAT: ${{ secrets.HUGO_BLOG_TOKEN }}
