# This is a basic workflow to help you get started with Actions

name: hugo deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Hugo setup
      uses: peaceiris/actions-hugo@v2.4.12
   
    - name: Build Hugo Site
      run: hugo --minify

    - name: Hugo gh-pages action
      uses: mattbailey/actions-hugo@v0.57.2
      with:
        github_token: ${{ secrets.HUGO_BLOG_TOKEN }}
        publish_branch: master
        publish_dir: ./public
