# This is a basic workflow to help you get started with Actions

name: hugo deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ hugo ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Hugo setup
      uses: peaceiris/actions-hugo@v2.4.12
   
    - name: Build Hugo Site
      run: hugo --minify

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
          github_token: ${{ secrets.HUGO_BLOG_TOKEN }}
          publish_branch: gh-pages  
          publish_dir: ./public
          
    - name: Hugo To medium Action step 
      uses: pr4k/Hugo-to-Medium@master # Uses an action in the root directory
      #id: hell
      env:
        ACCESS_TOKEN: ${{secrets.HUGO_BLOG_TOKEN}}
        APP_ID: ${{secrets.APP_ID}}
        APP_SECRET: ${{secrets.APP_SECRET}}
       # BLOG_DIR: ${{secrets.BLOG_DIR}}  
